[package]
name = "aiken-jna-wrapper"
version = "0.5.0"
authors = ["satran004", "matiwinnetou"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
aiken = "1.0.19-alpha"
uplc = "1.0.19-alpha"
aiken-lang = "1.0.19-alpha"

pallas-addresses = "0.18.2"
pallas-codec = "0.18.2"
pallas-crypto = "0.18.2"
pallas-primitives = "0.18.2"
pallas-traverse = "0.18.2"

ffi-support = "0.4.4"
jni = "0.20.0"
hex = "0.4.3"

minicbor = "0.19.1"
serde = { version = "1.0.95", features = ["derive"] }
serde_json = { version = "1.0.95" }
anyhow = "1.0.75"
