[package]
name = "aiken-jna-wrapper"
version = "0.9.0"
authors = ["Satya <satran004@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
aiken = "0.0.29"
uplc = "0.0.29"
aiken-lang = "0.0.29"
pallas-addresses = "0.16.0"
pallas-codec = "0.16.0"
pallas-crypto = "0.16.0"
pallas-primitives = "0.16.0"
pallas-traverse = "0.16.0"
ffi-support = "0.4.2"
jni = "0.20.0"
hex = "0.4.3"
minicbor = "0.18"
