[package]
name = "aiken-jna-wrapper"
version = "0.2.0"
authors = ["satran004", "matiwinnetou"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
aiken = { git = "https://github.com/txpipe/aiken.git", package = "aiken" }
uplc = { git = "https://github.com/txpipe/aiken.git", package = "uplc" }
aiken-lang = { git = "https://github.com/txpipe/aiken.git", package = "aiken-lang"}

pallas-addresses = "0.18.0"
pallas-codec = "0.18.0"
pallas-crypto = "0.18.0"
pallas-primitives = "0.18.0"
pallas-traverse = "0.18.0"
ffi-support = "0.4.4"
serde = { version = "1.0.95", features = ["derive"] }
serde_json = { version = "1.0.95" }
anyhow = "1.0.70"
jni = "0.20.0"
hex = "0.4.3"
minicbor = "0.19.1"